### ISSUE TITLE
/msas/ folder doesn't exist in data folder

### ISSUE THREAD

**Issue by bcntw** [v-mikhaylov/tfold-release#1]
Hi there. Thanks for sharing the code, I am trying to get it to run however I downloaded the zenodo archive and un-archived it and there is now data/msas folder which is needed to run the code to load /msas/mhc_msa_index.pckl.

**Comment by v-mikhaylov** [comment]
Oops, sorry! As a temporary workaround, I added msas.tar.gz to v-mikhaylov/tfold-full. Please download it from there and unpack in the data folder.

**Comment by v-mikhaylov** [comment]
I updated zenodo repository.
