### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by stefankraemer91** [v-mikhaylov/tfold-release#3]
Hi,
super interesting project. I am looking forward to try it out. Unfortunately, I get the following error message while setting up the environment:

`Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - bioconda::kalign2=2.04
  - cudatoolkit=11.0
  - cudnn=8.2`
  
  I am working on an Mac ARM computer. I understand that the packages are not really of use for me since I do not have a nvidea grafic card. Hence, I think I need to run the project on my CPU. Is there a way to modify the code in order to mac it run on a mac as well? If not. What are the hardware and OS requirements to install and run this project?

**Comment by v-mikhaylov** [comment]
Hi, thank you for your interest in this project! To run this tool, you need AlphaFold v. 2.1.0. The official AlphaFold GitHub account says that you need Linux and NVIDIA GPU for that. Unfortunately, I don't know if it is possible to run AlphaFold on a Mac.

**Comment by stefankraemer91** [comment]
Thanks. I thought so.
