### ISSUE TITLE
issue with running peptides with sequence

### ISSUE THREAD

**Issue by seanwangsalad** [v-mikhaylov/tfold-release#5]
Hello developers,

Great software! I was able to run many peptides. However, when running peptides using a sequence, I am getting an error (below). I attached my test1.csv file. I have pep and MHCII sequence separated by a /

If I changed MHC sequence to MHC allele and use HLA-DRA*01:01/DRB1*01:01, it runs.

[test1.csv](https://github.com/v-mikhaylov/tfold-release/files/14323279/test1.csv)

Aligning MHC sequences.
Traceback (most recent call last):
  File "/choncc/tfold-release/tfold/modeling/make_inputs.py", line 211, in map_one_mhc_seq
    mhc_a=seq_tools.mhc_from_seq(sA)
  File "/choncc/tfold-release/tfold/utils/seq_tools.py", line 614, in mhc_from_seq
    hits=blast_prot(seq,['MHC'],species=species)
  File "/choncc/tfold-release/tfold/utils/seq_tools.py", line 433, in blast_prot
    stdout,stderr=blastp_cline()
  File "/home/mhc/miniforge3/envs/tfold-env/lib/python3.8/site-packages/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 127 from 'blastp -out /choncc/tfold-release/tmp/IKEEHVIIQA5137303316.xml -outfmt 5 -query /choncc/tfold-release/tmp/IKEEHVIIQA5137303316.fasta -db /choncc/tfold-release/data/seq_tools/db/MHC.fasta', message '/bin/sh: 1: blastp: not found'

Thanks!

**Comment by v-mikhaylov** [comment]
Hi Sean! To align MHC to IMGT numbering, it uses blastp. You need to install BLAST and make sure `blastp` is available as a command line command. The version that I used was "Protein-Protein BLAST 2.9.0+" -- not sure if it works with the newer ones.

**Comment by seanwangsalad** [comment]
Sorry for the delayed response (got busy with school) This works! Thanks
