### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by samsaard** [v-mikhaylov/tfold-release#7]
Hi, 
I am very new to this field and attempting to set up a new environment using conda to replicate the TFold pipeline and AlphaFold processes as described in the documentation. However, I encountered an error when trying to create the environment with the provided yml file.

(base) C:\Users\Desktop>conda env create --file tfold-env.yml
Channels:
 - conda-forge
 - defaults
 - bioconda
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bioconda::kalign2==2.04

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by v-mikhaylov** [comment]
Hi! I think the issue is this: "Platform: win-64". You will not be able to install kalign2 or AlphaFold under Windows. You need Linux
