### ISSUE TITLE
iptm and ptm directories

### ISSUE THREAD

**Issue by bnidhish** [v-mikhaylov/tfold-release#9]
Hi, could you let me know where in the output or tfold-release directory I can find the iptm and ptm scores for my models? I'm trying to present their validity in accuracy and would like to collect them. Thank you so much in advance!

**Comment by v-mikhaylov** [comment]
Hi, by default, the algorithm uses AF2 model_1 which does not compute pTM/pAE. (It does compute and output pLDDT though.) You can try switching to model_1_ptm in tfold_patch/tfold_config.py/af_params['model_names'] and see if you get pTM/pAE in the pickled file that AF2 outputs. I haven't tried that.

**Comment by bnidhish** [comment]
Okay, thanks! I’ll make sure to try that
